#!/bin/bash
if [ $# -eq 2 ]
then 
	java -cp ".:./jarfile/slf4j-api-1.7.25.jar:./jarfile/slf4j-simple-1.7.25.jar:./jarfile/zookeeper-3.4.12.jar" player $@
elif [ $# -eq 5 ]
then
	java -cp ".:./jarfile/slf4j-api-1.7.25.jar:./jarfile/slf4j-simple-1.7.25.jar:./jarfile/zookeeper-3.4.12.jar" player $@
else
	echo "Usage: player <IP[:port] <player_name> [<count>] [<delay>] [<score>]>"
fi
